### ISSUE TITLE
Moving static models sometimes doesn't update the visual in gzclient

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gazebo-classic#1571]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/1571)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
@jacquelinekay found this bug when trying to move static models via the `ArrangePlugin`. Her particular scenario had lots of models (like the [wood_block_stack](#!/osrf/gazebo_models/src/toy_stack/wood_block_stack/model.sdf)), so the system was under heavy load. The server would always register the object move, but it wasn't always reflected in the GUI visual location.

I think static models may only send one pose update message, so perhaps the message got dropped?

@iche033 had some insight as well.

**Comment by scpeters** [comment]
this is identical to #2560, and while this was posted earlier, that one has more useful info, so I'll close this
